version: '3'
services:
  mysql:
    build: ./mysql
    ports: 
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    volumes:
      - /data/mysql/data:/var/lib/mysql
    networks:
       ZXQ:
        aliases:
         - mysql-server
  redis:
    image: redis:3.2
    restart: always    
    networks:
       ZXQ:
        aliases:
        - redis-server
  flask:
    build: ./flask
    ports:
      - 8000:8080
    networks:
      - ZXQ
    restart: always
  nginx: 
    build: ./nginx 
    ports: 
      - "80:80" 
    networks:
      - ZXQ
networks:
  ZXQ:
