# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GroupsInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, group_id: str=None, group_name: str=None):  # noqa: E501
        """GroupsInner - a model defined in Swagger

        :param group_id: The group_id of this GroupsInner.  # noqa: E501
        :type group_id: str
        :param group_name: The group_name of this GroupsInner.  # noqa: E501
        :type group_name: str
        """
        self.swagger_types = {
            'group_id': str,
            'group_name': str
        }

        self.attribute_map = {
            'group_id': 'groupId',
            'group_name': 'groupName'
        }

        self._group_id = group_id
        self._group_name = group_name

    @classmethod
    def from_dict(cls, dikt) -> 'GroupsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Groups_inner of this GroupsInner.  # noqa: E501
        :rtype: GroupsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_id(self) -> str:
        """Gets the group_id of this GroupsInner.


        :return: The group_id of this GroupsInner.
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id: str):
        """Sets the group_id of this GroupsInner.


        :param group_id: The group_id of this GroupsInner.
        :type group_id: str
        """

        self._group_id = group_id

    @property
    def group_name(self) -> str:
        """Gets the group_name of this GroupsInner.


        :return: The group_name of this GroupsInner.
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name: str):
        """Sets the group_name of this GroupsInner.


        :param group_name: The group_name of this GroupsInner.
        :type group_name: str
        """

        self._group_name = group_name
