# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.iden_info import IdenInfo  # noqa: F401,E501
from swagger_server import util


class IdenInfoWithCredit(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, iden_info: IdenInfo = None, credit_score: int = None
    ):  # noqa: E501
        """IdenInfoWithCredit - a model defined in Swagger

        :param iden_info: The iden_info of this IdenInfoWithCredit.  # noqa: E501
        :type iden_info: IdenInfo
        :param credit_score: The credit_score of this IdenInfoWithCredit.  # noqa: E501
        :type credit_score: int
        """
        self.swagger_types = {"iden_info": IdenInfo, "credit_score": int}

        self.attribute_map = {"iden_info": "idenInfo", "credit_score": "creditScore"}

        self._iden_info = iden_info
        self._credit_score = credit_score

    @classmethod
    def from_dict(cls, dikt) -> "IdenInfoWithCredit":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IdenInfoWithCredit of this IdenInfoWithCredit.  # noqa: E501
        :rtype: IdenInfoWithCredit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def iden_info(self) -> IdenInfo:
        """Gets the iden_info of this IdenInfoWithCredit.


        :return: The iden_info of this IdenInfoWithCredit.
        :rtype: IdenInfo
        """
        return self._iden_info

    @iden_info.setter
    def iden_info(self, iden_info: IdenInfo):
        """Sets the iden_info of this IdenInfoWithCredit.


        :param iden_info: The iden_info of this IdenInfoWithCredit.
        :type iden_info: IdenInfo
        """

        self._iden_info = iden_info

    @property
    def credit_score(self) -> int:
        """Gets the credit_score of this IdenInfoWithCredit.


        :return: The credit_score of this IdenInfoWithCredit.
        :rtype: int
        """
        return self._credit_score

    @credit_score.setter
    def credit_score(self, credit_score: int):
        """Sets the credit_score of this IdenInfoWithCredit.


        :param credit_score: The credit_score of this IdenInfoWithCredit.
        :type credit_score: int
        """

        self._credit_score = credit_score
