# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProveState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, prove_state: str = None):  # noqa: E501
        """ProveState - a model defined in Swagger

        :param prove_state: The prove_state of this ProveState.  # noqa: E501
        :type prove_state: str
        """
        self.swagger_types = {"prove_state": str}

        self.attribute_map = {"prove_state": "proveState"}

        self._prove_state = prove_state

    @classmethod
    def from_dict(cls, dikt) -> "ProveState":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProveState of this ProveState.  # noqa: E501
        :rtype: ProveState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prove_state(self) -> str:
        """Gets the prove_state of this ProveState.


        :return: The prove_state of this ProveState.
        :rtype: str
        """
        return self._prove_state

    @prove_state.setter
    def prove_state(self, prove_state: str):
        """Sets the prove_state of this ProveState.


        :param prove_state: The prove_state of this ProveState.
        :type prove_state: str
        """

        self._prove_state = prove_state
