# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserInfoWithoutId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, nick_name: str=None, avart_url: str=None):  # noqa: E501
        """UserInfoWithoutId - a model defined in Swagger

        :param nick_name: The nick_name of this UserInfoWithoutId.  # noqa: E501
        :type nick_name: str
        :param avart_url: The avart_url of this UserInfoWithoutId.  # noqa: E501
        :type avart_url: str
        """
        self.swagger_types = {
            'nick_name': str,
            'avart_url': str
        }

        self.attribute_map = {
            'nick_name': 'nickName',
            'avart_url': 'avartUrl'
        }

        self._nick_name = nick_name
        self._avart_url = avart_url

    @classmethod
    def from_dict(cls, dikt) -> 'UserInfoWithoutId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInfoWithoutId of this UserInfoWithoutId.  # noqa: E501
        :rtype: UserInfoWithoutId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nick_name(self) -> str:
        """Gets the nick_name of this UserInfoWithoutId.


        :return: The nick_name of this UserInfoWithoutId.
        :rtype: str
        """
        return self._nick_name

    @nick_name.setter
    def nick_name(self, nick_name: str):
        """Sets the nick_name of this UserInfoWithoutId.


        :param nick_name: The nick_name of this UserInfoWithoutId.
        :type nick_name: str
        """

        self._nick_name = nick_name

    @property
    def avart_url(self) -> str:
        """Gets the avart_url of this UserInfoWithoutId.


        :return: The avart_url of this UserInfoWithoutId.
        :rtype: str
        """
        return self._avart_url

    @avart_url.setter
    def avart_url(self, avart_url: str):
        """Sets the avart_url of this UserInfoWithoutId.


        :param avart_url: The avart_url of this UserInfoWithoutId.
        :type avart_url: str
        """

        self._avart_url = avart_url
