# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserInfoWithTel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, avart_url: str=None, nick_name: str=None, tel: str=None):  # noqa: E501
        """UserInfoWithTel - a model defined in Swagger

        :param avart_url: The avart_url of this UserInfoWithTel.  # noqa: E501
        :type avart_url: str
        :param nick_name: The nick_name of this UserInfoWithTel.  # noqa: E501
        :type nick_name: str
        :param tel: The tel of this UserInfoWithTel.  # noqa: E501
        :type tel: str
        """
        self.swagger_types = {
            'avart_url': str,
            'nick_name': str,
            'tel': str
        }

        self.attribute_map = {
            'avart_url': 'avartUrl',
            'nick_name': 'nickName',
            'tel': 'tel'
        }

        self._avart_url = avart_url
        self._nick_name = nick_name
        self._tel = tel

    @classmethod
    def from_dict(cls, dikt) -> 'UserInfoWithTel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInfoWithTel of this UserInfoWithTel.  # noqa: E501
        :rtype: UserInfoWithTel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def avart_url(self) -> str:
        """Gets the avart_url of this UserInfoWithTel.


        :return: The avart_url of this UserInfoWithTel.
        :rtype: str
        """
        return self._avart_url

    @avart_url.setter
    def avart_url(self, avart_url: str):
        """Sets the avart_url of this UserInfoWithTel.


        :param avart_url: The avart_url of this UserInfoWithTel.
        :type avart_url: str
        """

        self._avart_url = avart_url

    @property
    def nick_name(self) -> str:
        """Gets the nick_name of this UserInfoWithTel.


        :return: The nick_name of this UserInfoWithTel.
        :rtype: str
        """
        return self._nick_name

    @nick_name.setter
    def nick_name(self, nick_name: str):
        """Sets the nick_name of this UserInfoWithTel.


        :param nick_name: The nick_name of this UserInfoWithTel.
        :type nick_name: str
        """

        self._nick_name = nick_name

    @property
    def tel(self) -> str:
        """Gets the tel of this UserInfoWithTel.


        :return: The tel of this UserInfoWithTel.
        :rtype: str
        """
        return self._tel

    @tel.setter
    def tel(self, tel: str):
        """Sets the tel of this UserInfoWithTel.


        :param tel: The tel of this UserInfoWithTel.
        :type tel: str
        """

        self._tel = tel
