# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserInfoWithTel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        user_id: str = None,
        avatar_url: str = None,
        nick_name: str = None,
        tel: str = None,
    ):  # noqa: E501
        """UserInfoWithTel - a model defined in Swagger

        :param user_id: The user_id of this UserInfoWithTel.  # noqa: E501
        :type user_id: str
        :param avatar_url: The avatar_url of this UserInfoWithTel.  # noqa: E501
        :type avatar_url: str
        :param nick_name: The nick_name of this UserInfoWithTel.  # noqa: E501
        :type nick_name: str
        :param tel: The tel of this UserInfoWithTel.  # noqa: E501
        :type tel: str
        """
        self.swagger_types = {
            "user_id": str,
            "avatar_url": str,
            "nick_name": str,
            "tel": str,
        }

        self.attribute_map = {
            "user_id": "userId",
            "avatar_url": "avatarUrl",
            "nick_name": "nickName",
            "tel": "tel",
        }

        self._user_id = user_id
        self._avatar_url = avatar_url
        self._nick_name = nick_name
        self._tel = tel

    @classmethod
    def from_dict(cls, dikt) -> "UserInfoWithTel":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInfoWithTel of this UserInfoWithTel.  # noqa: E501
        :rtype: UserInfoWithTel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserInfoWithTel.


        :return: The user_id of this UserInfoWithTel.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserInfoWithTel.


        :param user_id: The user_id of this UserInfoWithTel.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def avatar_url(self) -> str:
        """Gets the avatar_url of this UserInfoWithTel.


        :return: The avatar_url of this UserInfoWithTel.
        :rtype: str
        """
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url: str):
        """Sets the avatar_url of this UserInfoWithTel.


        :param avatar_url: The avatar_url of this UserInfoWithTel.
        :type avatar_url: str
        """

        self._avatar_url = avatar_url

    @property
    def nick_name(self) -> str:
        """Gets the nick_name of this UserInfoWithTel.


        :return: The nick_name of this UserInfoWithTel.
        :rtype: str
        """
        return self._nick_name

    @nick_name.setter
    def nick_name(self, nick_name: str):
        """Sets the nick_name of this UserInfoWithTel.


        :param nick_name: The nick_name of this UserInfoWithTel.
        :type nick_name: str
        """

        self._nick_name = nick_name

    @property
    def tel(self) -> str:
        """Gets the tel of this UserInfoWithTel.


        :return: The tel of this UserInfoWithTel.
        :rtype: str
        """
        return self._tel

    @tel.setter
    def tel(self, tel: str):
        """Sets the tel of this UserInfoWithTel.


        :param tel: The tel of this UserInfoWithTel.
        :type tel: str
        """

        self._tel = tel
